/* Ракета — демо-каталог. Плейсхолдер-данные до подключения реального
   товарного фида/API поставщика: структура повторяет будущий API,
   чтобы замена свелась к одному источнику данных. */
(function () {
  'use strict';

  var CATEGORIES = [
    { id: 'smartphones', name: 'Смартфоны', art: 'phone', tone: 'titan', blurb: 'Флагманы и надёжные середняки с официальной гарантией' },
    { id: 'laptops', name: 'Ноутбуки и планшеты', art: 'laptop', tone: 'graphite', blurb: 'Для работы, учёбы и творчества' },
    { id: 'tv', name: 'Телевизоры', art: 'tv', tone: 'graphite', blurb: 'OLED, QLED и 4K для любого бюджета' },
    { id: 'audio', name: 'Аудио и наушники', art: 'headphones', tone: 'black', blurb: 'Звук, который хочется слушать' },
    { id: 'gaming', name: 'Гейминг', art: 'gamepad', tone: 'graphite', blurb: 'Консоли, аксессуары и периферия' },
    { id: 'appliances-big', name: 'Крупная техника', art: 'fridge', tone: 'steel', blurb: 'Холодильники, стирка, встройка' },
    { id: 'appliances-small', name: 'Мелкая техника', art: 'coffee', tone: 'graphite', blurb: 'Кухня, уборка и уход' },
    { id: 'smart-home', name: 'Умный дом', art: 'station', tone: 'midnight', blurb: 'Станции, датчики и умный свет' },
    { id: 'accessories', name: 'Аксессуары', art: 'phonecase', tone: 'midnight', blurb: 'Чехлы, зарядки, кабели и защита' }
  ];

  function P(o) {
    o.old = o.old || 0;
    o.rating = o.rating || 4.7;
    o.votes = o.votes || 12;
    o.specs = o.specs || [];
    return o;
  }

  var PRODUCTS = [
    /* ---------- Смартфоны ---------- */
    P({ id: 'ip16pro', cat: 'smartphones', brand: 'Apple', name: 'iPhone 16 Pro 128 ГБ, чёрный титан', price: 119990, art: 'phone', tone: 'graphite', img: 'assets/products/iphone.png',
      hit: true, featured: true, rating: 4.9, votes: 64,
      desc: 'Титановый корпус, чип A18 Pro и лучшая камера в линейке. Кнопка управления камерой и Always-On дисплей.',
      specs: [['Дисплей', '6.3" OLED, 120 Гц, 2622×1206'], ['Процессор', 'Apple A18 Pro'], ['Память', '128 ГБ'], ['Камера', '48 + 48 + 12 Мп, 5x зум'], ['Аккумулятор', 'до 27 ч видео'], ['Гарантия', '1 год']],
      acc: ['acc-case-16pro', 'acc-glass', 'acc-magsafe', 'acc-adapter30'],
      bundle: { items: ['acc-case-16pro', 'acc-glass'], save: 1990 } }),
    P({ id: 'ip16', cat: 'smartphones', brand: 'Apple', name: 'iPhone 16 128 ГБ, ультрамарин', price: 89990, art: 'phone', tone: 'blue',
      isnew: true, rating: 4.9, votes: 41,
      desc: 'Чип A18, Camera Control и новые цвета. Оптимальный iPhone поколения.',
      specs: [['Дисплей', '6.1" OLED, 2556×1179'], ['Процессор', 'Apple A18'], ['Память', '128 ГБ'], ['Камера', '48 + 12 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-case-16pro', 'acc-glass', 'acc-magsafe', 'acc-adapter30'] }),
    P({ id: 'ip15', cat: 'smartphones', brand: 'Apple', name: 'iPhone 15 128 ГБ, чёрный', price: 72990, old: 79990, art: 'phone', tone: 'graphite',
      rating: 4.8, votes: 58,
      desc: 'Проверенная классика: Dynamic Island, камера 48 Мп и USB-C.',
      specs: [['Дисплей', '6.1" OLED'], ['Процессор', 'Apple A16 Bionic'], ['Память', '128 ГБ'], ['Камера', '48 + 12 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-glass', 'acc-magsafe', 'acc-adapter30', 'acc-pb10'] }),
    P({ id: 's24u', cat: 'smartphones', brand: 'Samsung', name: 'Galaxy S24 Ultra 256 ГБ, серый титан', price: 109990, old: 119990, art: 'phone', tone: 'graphite',
      hit: true, rating: 4.8, votes: 47,
      desc: 'Galaxy AI, стилус S Pen и камера 200 Мп. Титановая рама и плоский экран 6.8".',
      specs: [['Дисплей', '6.8" AMOLED, 120 Гц'], ['Процессор', 'Snapdragon 8 Gen 3'], ['Память', '12/256 ГБ'], ['Камера', '200 + 50 + 12 + 10 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-case-s24u', 'acc-glass', 'acc-pb10', 'acc-cable'],
      bundle: { items: ['acc-case-s24u', 'acc-glass'], save: 1490 } }),
    P({ id: 'a55', cat: 'smartphones', brand: 'Samsung', name: 'Galaxy A55 8/256 ГБ, лаванда', price: 34990, art: 'phone', tone: 'sky',
      rating: 4.7, votes: 33,
      desc: 'Металлическая рама, яркий AMOLED и 4 года обновлений.',
      specs: [['Дисплей', '6.6" AMOLED, 120 Гц'], ['Процессор', 'Exynos 1480'], ['Память', '8/256 ГБ'], ['Камера', '50 + 12 + 5 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-glass', 'acc-cable', 'acc-pb10'] }),
    P({ id: 'x14t', cat: 'smartphones', brand: 'Xiaomi', name: 'Xiaomi 14T Pro 12/512 ГБ, чёрный', price: 54990, old: 59990, art: 'phone', tone: 'black',
      isnew: true, rating: 4.7, votes: 21,
      desc: 'Оптика Leica, зарядка 120 Вт и флагманский Dimensity 9300+.',
      specs: [['Дисплей', '6.67" AMOLED, 144 Гц'], ['Процессор', 'Dimensity 9300+'], ['Память', '12/512 ГБ'], ['Камера', 'Leica 50 + 50 + 12 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-glass', 'acc-cable', 'acc-pb10'] }),
    P({ id: 'rn13p', cat: 'smartphones', brand: 'Xiaomi', name: 'Redmi Note 13 Pro 8/256 ГБ, фиолетовый', price: 24990, art: 'phone', tone: 'midnight',
      rating: 4.6, votes: 52,
      desc: 'Камера 200 Мп и AMOLED-экран в народном сегменте.',
      specs: [['Дисплей', '6.67" AMOLED, 120 Гц'], ['Процессор', 'Helio G99 Ultra'], ['Память', '8/256 ГБ'], ['Камера', '200 + 8 + 2 Мп'], ['Гарантия', '1 год']],
      acc: ['acc-glass', 'acc-cable', 'acc-pb10'] }),
    P({ id: 'honor-x9b', cat: 'smartphones', brand: 'HONOR', name: 'HONOR X9b 8/256 ГБ, зелёный', price: 23990, art: 'phone', tone: 'sage',
      rating: 4.6, votes: 18,
      desc: 'Неубиваемый изогнутый экран и батарея 5800 мА·ч.',
      specs: [['Дисплей', '6.78" AMOLED, 120 Гц'], ['Процессор', 'Snapdragon 6 Gen 1'], ['Память', '8/256 ГБ'], ['Аккумулятор', '5800 мА·ч'], ['Гарантия', '1 год']],
      acc: ['acc-glass', 'acc-cable', 'acc-pb10'] }),

    /* ---------- Ноутбуки и планшеты ---------- */
    P({ id: 'mba13', cat: 'laptops', brand: 'Apple', name: 'MacBook Air 13" M3 8/256 ГБ, серый космос', price: 114990, art: 'laptop', tone: 'graphite', img: 'assets/products/macbook.png',
      hit: true, featured: true, rating: 4.9, votes: 39,
      desc: 'Бесшумный, тонкий и до 18 часов работы. Чип M3 тянет монтаж и разработку.',
      specs: [['Дисплей', '13.6" Liquid Retina'], ['Процессор', 'Apple M3, 8 ядер'], ['Память', '8 ГБ / SSD 256 ГБ'], ['Батарея', 'до 18 ч'], ['Вес', '1.24 кг'], ['Гарантия', '1 год']],
      acc: ['acc-bag14', 'acc-mouse', 'acc-hub', 'acc-adapter30'],
      bundle: { items: ['acc-bag14', 'acc-mouse'], save: 990 } }),
    P({ id: 'mbp14', cat: 'laptops', brand: 'Apple', name: 'MacBook Pro 14" M4 16/512 ГБ, серый космос', price: 189990, art: 'laptop', tone: 'graphite',
      rating: 5.0, votes: 14,
      desc: 'Экран Liquid Retina XDR 120 Гц и чип M4 для профессиональных задач.',
      specs: [['Дисплей', '14.2" XDR, 120 Гц'], ['Процессор', 'Apple M4, 10 ядер'], ['Память', '16 ГБ / SSD 512 ГБ'], ['Батарея', 'до 24 ч'], ['Гарантия', '1 год']],
      acc: ['acc-bag14', 'acc-mouse', 'acc-hub'] }),
    P({ id: 'vivobook15', cat: 'laptops', brand: 'ASUS', name: 'ASUS Vivobook 15 R7/16/512, серебристый', price: 54990, art: 'laptop', tone: 'silver',
      rating: 4.6, votes: 27,
      desc: 'Универсальный офисный ноутбук с быстрым Ryzen 7 и лёгким корпусом.',
      specs: [['Дисплей', '15.6" IPS, FHD'], ['Процессор', 'Ryzen 7 7730U'], ['Память', '16 ГБ / SSD 512 ГБ'], ['ОС', 'Без ОС'], ['Гарантия', '1 год']],
      acc: ['acc-bag14', 'acc-mouse', 'acc-hub'] }),
    P({ id: 'ideapad5', cat: 'laptops', brand: 'Lenovo', name: 'Lenovo IdeaPad Slim 5 OLED, серый', price: 62990, old: 69990, art: 'laptop', tone: 'steel',
      rating: 4.7, votes: 19,
      desc: 'OLED-экран и алюминиевый корпус по цене обычного IPS.',
      specs: [['Дисплей', '14" OLED, 2.8K'], ['Процессор', 'Core Ultra 5 125H'], ['Память', '16 ГБ / SSD 512 ГБ'], ['Вес', '1.46 кг'], ['Гарантия', '1 год']],
      acc: ['acc-bag14', 'acc-mouse', 'acc-hub'] }),
    P({ id: 'nitrov15', cat: 'laptops', brand: 'Acer', name: 'Acer Nitro V 15 RTX 4050, чёрный', price: 89990, art: 'laptop', tone: 'black',
      rating: 4.7, votes: 23,
      desc: 'Игровая карта RTX 4050 и экран 144 Гц: киберспорт и AAA на высоких.',
      specs: [['Дисплей', '15.6" IPS, 144 Гц'], ['Процессор', 'Core i5-13420H'], ['Видео', 'RTX 4050 6 ГБ'], ['Память', '16 ГБ / SSD 512 ГБ'], ['Гарантия', '1 год']],
      acc: ['g-mouse-g502', 'acc-bag14', 'g-arctis'] }),
    P({ id: 'ipad10', cat: 'laptops', brand: 'Apple', name: 'iPad 10.9" Wi-Fi 64 ГБ, голубой', price: 39990, art: 'tablet', tone: 'sky',
      rating: 4.8, votes: 36,
      desc: 'Планшет для всей семьи: учёба, фильмы, заметки и лёгкие игры.',
      specs: [['Дисплей', '10.9" Liquid Retina'], ['Процессор', 'Apple A14'], ['Память', '64 ГБ'], ['Гарантия', '1 год']],
      acc: ['acc-adapter30', 'acc-cable'] }),
    P({ id: 'ipadair11', cat: 'laptops', brand: 'Apple', name: 'iPad Air 11" M2 128 ГБ, звёздный', price: 64990, art: 'tablet', tone: 'silver',
      isnew: true, rating: 4.9, votes: 15,
      desc: 'Чип M2 и поддержка Apple Pencil Pro: планшет уровня ноутбука.',
      specs: [['Дисплей', '11" Liquid Retina'], ['Процессор', 'Apple M2'], ['Память', '128 ГБ'], ['Гарантия', '1 год']],
      acc: ['acc-adapter30', 'acc-cable'] }),

    /* ---------- Телевизоры ---------- */
    P({ id: 'lgc4-55', cat: 'tv', brand: 'LG', name: 'LG OLED evo C4 55", 4K 144 Гц', price: 129990, art: 'tv', tone: 'black', img: 'assets/products/lgtv.jpg', imgFit: 'cover',
      hit: true, featured: true, rating: 4.9, votes: 26,
      desc: 'Эталонный OLED: идеальный чёрный, 144 Гц для консолей и webOS.',
      specs: [['Диагональ', '55", OLED evo'], ['Разрешение', '4K, 144 Гц'], ['HDR', 'Dolby Vision, HDR10'], ['Smart TV', 'webOS 24'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi', 'acc-surge'],
      bundle: { items: ['acc-bracket', 'acc-hdmi'], save: 990 } }),
    P({ id: 'q70d-55', cat: 'tv', brand: 'Samsung', name: 'Samsung QLED Q70D 55", 4K 120 Гц', price: 89990, old: 99990, art: 'tv', tone: 'graphite',
      rating: 4.8, votes: 31,
      desc: 'Яркий QLED с игровым режимом 120 Гц и объёмным звуком.',
      specs: [['Диагональ', '55", QLED'], ['Разрешение', '4K, 120 Гц'], ['HDR', 'HDR10+'], ['Smart TV', 'Tizen'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi', 'acc-surge'] }),
    P({ id: 'du8000-50', cat: 'tv', brand: 'Samsung', name: 'Samsung Crystal UHD DU8000 50"', price: 45990, art: 'tv', tone: 'graphite',
      rating: 4.7, votes: 44,
      desc: 'Сбалансированный 4K-телевизор для гостиной: тонкий корпус, быстрый Smart TV.',
      specs: [['Диагональ', '50"'], ['Разрешение', '4K UHD'], ['Smart TV', 'Tizen'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi', 'acc-surge'] }),
    P({ id: 'hisense-u7', cat: 'tv', brand: 'Hisense', name: 'Hisense 55U7KQ Mini-LED 55"', price: 57990, art: 'tv', tone: 'black',
      rating: 4.7, votes: 17,
      desc: 'Mini-LED подсветка и 144 Гц по цене обычного LED.',
      specs: [['Диагональ', '55", Mini-LED'], ['Разрешение', '4K, 144 Гц'], ['HDR', 'Dolby Vision IQ'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi', 'acc-surge'] }),
    P({ id: 'mitv-a43', cat: 'tv', brand: 'Xiaomi', name: 'Xiaomi TV A 43" FHD', price: 24990, art: 'tv', tone: 'graphite',
      rating: 4.5, votes: 39,
      desc: 'Компактный телевизор для кухни или спальни с голосовым поиском.',
      specs: [['Диагональ', '43"'], ['Разрешение', 'Full HD'], ['Smart TV', 'Google TV'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi'] }),
    P({ id: 'tcl65-c655', cat: 'tv', brand: 'TCL', name: 'TCL 65C655 QLED 65"', price: 69990, old: 74990, art: 'tv', tone: 'black',
      isnew: true, rating: 4.6, votes: 12,
      desc: 'Большая диагональ QLED для домашнего кинотеатра.',
      specs: [['Диагональ', '65", QLED'], ['Разрешение', '4K'], ['HDR', 'Dolby Vision'], ['Гарантия', '1 год']],
      acc: ['acc-bracket', 'acc-hdmi', 'acc-surge'] }),

    /* ---------- Аудио ---------- */
    P({ id: 'airpods-pro2', cat: 'audio', brand: 'Apple', name: 'AirPods Pro 2 (USB-C)', price: 24990, art: 'buds', tone: 'white', img: 'assets/products/airpods.png',
      hit: true, rating: 4.9, votes: 61,
      desc: 'Лучшее шумоподавление в классе, адаптивный звук и чехол MagSafe.',
      specs: [['Тип', 'TWS, вкладыши'], ['ANC', 'Активное шумоподавление'], ['Время работы', 'до 30 ч с кейсом'], ['Гарантия', '1 год']],
      acc: ['acc-magsafe', 'acc-pb10'] }),
    P({ id: 'airpods4', cat: 'audio', brand: 'Apple', name: 'AirPods 4', price: 13990, art: 'buds', tone: 'white',
      isnew: true, rating: 4.7, votes: 22,
      desc: 'Новая посадка, чип H2 и чистый звук без затычек.',
      specs: [['Тип', 'TWS, вкладыши'], ['Время работы', 'до 30 ч с кейсом'], ['Гарантия', '1 год']],
      acc: ['acc-adapter30', 'acc-cable'] }),
    P({ id: 'sony-xm5', cat: 'audio', brand: 'Sony', name: 'Sony WH-1000XM5, чёрные', price: 32990, old: 36990, art: 'headphones', tone: 'black',
      featured: true, rating: 4.9, votes: 48,
      desc: 'Флагманские полноразмерные наушники: 30 часов работы и эталонный ANC.',
      specs: [['Тип', 'Полноразмерные, Bluetooth 5.2'], ['ANC', 'Процессор V1 + QN1'], ['Время работы', 'до 30 ч'], ['Кодеки', 'LDAC, AAC'], ['Гарантия', '1 год']],
      acc: ['acc-pb10', 'acc-cable'] }),
    P({ id: 'marshall-major5', cat: 'audio', brand: 'Marshall', name: 'Marshall Major V, чёрные', price: 12990, art: 'headphones', tone: 'black',
      isnew: true, rating: 4.7, votes: 16,
      desc: 'Рок-классика: 100+ часов работы и фирменный звук Marshall.',
      specs: [['Тип', 'Накладные, Bluetooth 5.3'], ['Время работы', 'до 100 ч'], ['Гарантия', '1 год']],
      acc: ['acc-pb10', 'acc-cable'] }),
    P({ id: 'jbl-t770', cat: 'audio', brand: 'JBL', name: 'JBL Tune 770NC, синие', price: 8990, art: 'headphones', tone: 'midnight',
      rating: 4.6, votes: 34,
      desc: 'Полноразмерные наушники с шумоподавлением и JBL Pure Bass.',
      specs: [['Тип', 'Полноразмерные'], ['ANC', 'Да'], ['Время работы', 'до 70 ч'], ['Гарантия', '1 год']],
      acc: ['acc-pb10', 'acc-cable'] }),
    P({ id: 'jbl-charge5', cat: 'audio', brand: 'JBL', name: 'JBL Charge 5, чёрная', price: 13990, art: 'speaker', tone: 'black',
      rating: 4.8, votes: 45,
      desc: 'Портативная колонка с мощным басом и функцией пауэрбанка. IP67.',
      specs: [['Мощность', '40 Вт'], ['Защита', 'IP67'], ['Время работы', 'до 20 ч'], ['Гарантия', '1 год']],
      acc: ['acc-pb10'] }),
    P({ id: 'marshall-emberton2', cat: 'audio', brand: 'Marshall', name: 'Marshall Emberton II, кремовая', price: 14990, art: 'boombox', tone: 'black',
      rating: 4.8, votes: 20,
      desc: 'Компактная колонка с звуком на 360° и легендарным дизайном.',
      specs: [['Мощность', '20 Вт'], ['Защита', 'IP67'], ['Время работы', 'до 30 ч'], ['Гарантия', '1 год']],
      acc: ['acc-pb10'] }),

    /* ---------- Гейминг ---------- */
    P({ id: 'ps5-slim', cat: 'gaming', brand: 'Sony', name: 'PlayStation 5 Slim, дисковод', price: 54990, art: 'console', tone: 'white', img: 'assets/products/ps5.png',
      hit: true, featured: true, rating: 4.9, votes: 53,
      desc: 'Обновлённая PS5: тише, компактнее, 1 ТБ памяти. В коробке DualSense.',
      specs: [['Накопитель', 'SSD 1 ТБ'], ['Разрешение', 'до 4K 120 fps'], ['Привод', 'Blu-ray'], ['Гарантия', '1 год']],
      acc: ['g-dualsense2', 'acc-hdmi', 'g-arctis'],
      bundle: { items: ['g-dualsense2'], save: 1500 } }),
    P({ id: 'g-dualsense2', cat: 'gaming', brand: 'Sony', name: 'Геймпад DualSense, белый', price: 6490, art: 'gamepad', tone: 'white',
      rating: 4.8, votes: 40,
      desc: 'Адаптивные курки и отдача, которую чувствуешь кожей.',
      specs: [['Подключение', 'Bluetooth / USB-C'], ['Совместимость', 'PS5, ПК'], ['Гарантия', '1 год']],
      acc: ['acc-cable'] }),
    P({ id: 'switch-oled', cat: 'gaming', brand: 'Nintendo', name: 'Nintendo Switch OLED, неон', price: 32990, art: 'switchcon', tone: 'graphite',
      isnew: true, rating: 4.8, votes: 29,
      desc: 'Гибридная консоль с ярким OLED-экраном: дома и в дороге.',
      specs: [['Экран', '7" OLED'], ['Память', '64 ГБ'], ['Режимы', 'ТВ / портатив'], ['Гарантия', '1 год']],
      acc: ['acc-hdmi', 'acc-pb10'] }),
    P({ id: 'xbox-s', cat: 'gaming', brand: 'Microsoft', name: 'Xbox Series S 512 ГБ, белый', price: 29990, art: 'console', tone: 'white',
      rating: 4.7, votes: 25,
      desc: 'Компактный некстген: Game Pass и сотни игр по подписке.',
      specs: [['Накопитель', 'SSD 512 ГБ'], ['Разрешение', 'до 1440p 120 fps'], ['Гарантия', '1 год']],
      acc: ['acc-hdmi', 'g-arctis'] }),
    P({ id: 'g-mouse-g502', cat: 'gaming', brand: 'Logitech', name: 'Мышь Logitech G502 X, чёрная', price: 7990, art: 'mouse', tone: 'black',
      rating: 4.8, votes: 37,
      desc: 'Легенда киберспорта: сенсор HERO 25K и гибридные переключатели.',
      specs: [['Сенсор', 'HERO 25K'], ['Кнопки', '13 программируемых'], ['Гарантия', '2 года']],
      acc: [] }),
    P({ id: 'g-arctis', cat: 'gaming', brand: 'SteelSeries', name: 'Гарнитура SteelSeries Arctis Nova 3', price: 11990, art: 'headset', tone: 'black',
      rating: 4.7, votes: 14,
      desc: 'Чистый звук ClearCast и комфорт на длинные сессии.',
      specs: [['Подключение', 'USB-C'], ['Микрофон', 'Выдвижной, ClearCast Gen 2'], ['Гарантия', '1 год']],
      acc: [] }),

    /* ---------- Крупная техника ---------- */
    P({ id: 'bosch-kgn39', cat: 'appliances-big', brand: 'Bosch', name: 'Холодильник Bosch Serie 4 KGN39, нерж.', price: 79990, art: 'fridge', tone: 'steel',
      featured: true, rating: 4.8, votes: 23,
      desc: 'NoFrost, зона свежести VitaFresh и тихая работа 39 дБ.',
      specs: [['Объём', '368 л'], ['Система', 'NoFrost'], ['Класс', 'A, 39 дБ'], ['Размеры', '203×60×66 см'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'lg-f2v5', cat: 'appliances-big', brand: 'LG', name: 'Стиральная машина LG AI DD 8 кг', price: 54990, old: 59990, art: 'washer', tone: 'white',
      rating: 4.8, votes: 35,
      desc: 'Искусственный интеллект подбирает режим под ткань. Пар Steam.',
      specs: [['Загрузка', '8 кг'], ['Отжим', '1200 об/мин'], ['Мотор', 'AI Direct Drive'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'bosch-spv4', cat: 'appliances-big', brand: 'Bosch', name: 'Посудомоечная машина Bosch 45 см встр.', price: 46990, art: 'dishwasher', tone: 'steel',
      rating: 4.7, votes: 19,
      desc: 'Вмещает 10 комплектов, луч на полу и защита от протечек.',
      specs: [['Ширина', '45 см'], ['Комплектов', '10'], ['Расход', '9.5 л'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'weissgauff-hi64', cat: 'appliances-big', brand: 'Weissgauff', name: 'Индукционная панель Weissgauff HI 643', price: 24990, art: 'cooktop', tone: 'black',
      rating: 4.6, votes: 16,
      desc: 'Быстрый нагрев, слайдер-управление и таймер на каждую конфорку.',
      specs: [['Конфорки', '4, индукция'], ['Управление', 'Сенсорное'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'electrolux-ezb', cat: 'appliances-big', brand: 'Electrolux', name: 'Духовой шкаф Electrolux SurroundCook', price: 39990, art: 'oven', tone: 'black',
      rating: 4.7, votes: 13,
      desc: 'Равномерная конвекция и каталитическая очистка.',
      specs: [['Объём', '65 л'], ['Очистка', 'Каталитическая'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'haier-as20', cat: 'appliances-big', brand: 'Haier', name: 'Кондиционер Haier Flexis 20 м²', price: 35990, art: 'ac', tone: 'white',
      rating: 4.7, votes: 21,
      desc: 'Инверторная сплит-система с Wi-Fi и самоочисткой.',
      specs: [['Площадь', 'до 20 м²'], ['Тип', 'Инвертор'], ['Управление', 'Wi-Fi'], ['Гарантия', '3 года']],
      acc: ['acc-surge'] }),

    /* ---------- Мелкая техника ---------- */
    P({ id: 'roborock-q8', cat: 'appliances-small', brand: 'Roborock', name: 'Робот-пылесос Roborock Q8 Max', price: 32990, art: 'robot', tone: 'white',
      hit: true, rating: 4.8, votes: 42,
      desc: 'Лидар-навигация, влажная уборка и 5700 Па мощности.',
      specs: [['Мощность', '5700 Па'], ['Навигация', 'LiDAR'], ['Уборка', 'Сухая + влажная'], ['Гарантия', '1 год']],
      acc: ['acc-surge'] }),
    P({ id: 'dyson-v15', cat: 'appliances-small', brand: 'Dyson', name: 'Пылесос Dyson V15 Detect', price: 54990, art: 'stickvac', tone: 'graphite',
      featured: true, rating: 4.9, votes: 28,
      desc: 'Лазер подсвечивает пыль, датчик считает частицы. До 60 минут работы.',
      specs: [['Мощность', '240 аВт'], ['Время работы', 'до 60 мин'], ['Контейнер', '0.77 л'], ['Гарантия', '2 года']],
      acc: [] }),
    P({ id: 'delonghi-magnifica', cat: 'appliances-small', brand: "De'Longhi", name: "Кофемашина De'Longhi Magnifica S", price: 49990, old: 54990, art: 'coffee', tone: 'black',
      rating: 4.8, votes: 31,
      desc: 'Зерновой эспрессо и капучино дома: 13 степеней помола, капучинатор.',
      specs: [['Тип', 'Автоматическая'], ['Давление', '15 бар'], ['Кофемолка', '13 степеней'], ['Гарантия', '2 года']],
      acc: ['acc-surge'] }),
    P({ id: 'dyson-ssonic', cat: 'appliances-small', brand: 'Dyson', name: 'Фен Dyson Supersonic HD08', price: 39990, art: 'hairdryer', tone: 'graphite',
      rating: 4.8, votes: 24,
      desc: 'Быстрая сушка без перегрева волос. 5 насадок в комплекте.',
      specs: [['Мощность', '1600 Вт'], ['Режимы', '4 скорости, 3 температуры'], ['Гарантия', '2 года']],
      acc: [] }),
    P({ id: 'mi-kettle', cat: 'appliances-small', brand: 'Xiaomi', name: 'Чайник Xiaomi Electric Kettle 2, белый', price: 2990, art: 'kettle', tone: 'white',
      rating: 4.6, votes: 48,
      desc: 'Сталь внутри, минимализм снаружи. Кипятит за 4 минуты.',
      specs: [['Объём', '1.7 л'], ['Мощность', '1800 Вт'], ['Гарантия', '1 год']],
      acc: [] }),
    P({ id: 'polaris-pmc', cat: 'appliances-small', brand: 'Polaris', name: 'Мультиварка Polaris PMC 0526, чёрная', price: 8990, art: 'multicooker', tone: 'black',
      rating: 4.6, votes: 26,
      desc: '21 программа, чаша 5 литров и отложенный старт.',
      specs: [['Объём', '5 л'], ['Программ', '21'], ['Гарантия', '1 год']],
      acc: [] }),
    P({ id: 'bosch-blender', cat: 'appliances-small', brand: 'Bosch', name: 'Блендер Bosch VitaPower, серебристый', price: 5490, art: 'blender', tone: 'steel',
      rating: 4.5, votes: 17,
      desc: 'Смузи и супы-пюре: 1200 Вт и кувшин ThermoSafe.',
      specs: [['Мощность', '1200 Вт'], ['Кувшин', '1.5 л, стекло'], ['Гарантия', '1 год']],
      acc: [] }),

    /* ---------- Умный дом ---------- */
    P({ id: 'station2', cat: 'smart-home', brand: 'Яндекс', name: 'Яндекс Станция 2, антрацит', price: 16990, art: 'station', tone: 'graphite',
      hit: true, featured: true, rating: 4.8, votes: 57,
      desc: 'Умная колонка с Алисой: музыка, умный дом и Zigbee-хаб внутри.',
      specs: [['Мощность', '30 Вт'], ['Ассистент', 'Алиса'], ['Хаб', 'Zigbee'], ['Гарантия', '1 год']],
      acc: ['sh-bulb', 'sh-plug', 'sh-cam'],
      bundle: { items: ['sh-bulb', 'sh-plug'], save: 690 } }),
    P({ id: 'station-mini3', cat: 'smart-home', brand: 'Яндекс', name: 'Яндекс Станция Мини 3, серая', price: 7990, art: 'ministation', tone: 'silver',
      rating: 4.7, votes: 49,
      desc: 'Компактная Алиса для кухни или спальни. Часы и жесты.',
      specs: [['Мощность', '10 Вт'], ['Ассистент', 'Алиса'], ['Гарантия', '1 год']],
      acc: ['sh-bulb', 'sh-plug'] }),
    P({ id: 'sh-bulb', cat: 'smart-home', brand: 'Yeelight', name: 'Умная лампа Yeelight E27, мультицвет', price: 1990, art: 'bulb', tone: 'white',
      rating: 4.6, votes: 38,
      desc: '16 млн цветов, сценарии и голосовое управление.',
      specs: [['Цоколь', 'E27'], ['Яркость', '800 лм'], ['Гарантия', '1 год']],
      acc: [] }),
    P({ id: 'sh-cam', cat: 'smart-home', brand: 'Xiaomi', name: 'Камера Xiaomi Smart Camera C300', price: 3490, art: 'cam', tone: 'white',
      rating: 4.7, votes: 30,
      desc: '2K-обзор на 360°, ночная съёмка и детекция людей.',
      specs: [['Разрешение', '2K'], ['Обзор', '360°'], ['Гарантия', '1 год']],
      acc: [] }),
    P({ id: 'sh-plug', cat: 'smart-home', brand: 'Яндекс', name: 'Умная розетка Яндекс, белая', price: 1290, art: 'plug', tone: 'white',
      rating: 4.6, votes: 44,
      desc: 'Управляйте любой техникой с телефона или голосом.',
      specs: [['Нагрузка', 'до 16 А'], ['Протокол', 'Wi-Fi'], ['Гарантия', '1 год']],
      acc: [] }),

    /* ---------- Аксессуары ---------- */
    P({ id: 'acc-case-16pro', cat: 'accessories', brand: 'Apple', name: 'Чехол MagSafe для iPhone 16 Pro, синий', price: 2990, art: 'phonecase', tone: 'midnight', rating: 4.7, votes: 26, desc: 'Плотная посадка, магниты MagSafe и мягкая микрофибра внутри.', specs: [['Совместимость', 'iPhone 16 Pro'], ['Материал', 'Силикон']] }),
    P({ id: 'acc-case-s24u', cat: 'accessories', brand: 'Samsung', name: 'Чехол для Galaxy S24 Ultra, чёрный', price: 1990, art: 'phonecase', tone: 'black', rating: 4.6, votes: 18, desc: 'Тонкий чехол с защитой камеры.', specs: [['Совместимость', 'Galaxy S24 Ultra']] }),
    P({ id: 'acc-glass', cat: 'accessories', brand: 'BoraSCO', name: 'Защитное стекло 2.5D, прозрачное', price: 990, art: 'glass', tone: 'silver', rating: 4.5, votes: 52, desc: 'Олеофобное покрытие и твёрдость 9H. Наклеим бесплатно при покупке.', specs: [['Твёрдость', '9H']] }),
    P({ id: 'acc-adapter30', cat: 'accessories', brand: 'Apple', name: 'Адаптер питания USB-C 30 Вт', price: 3490, art: 'charger', tone: 'white', rating: 4.8, votes: 33, desc: 'Быстрая зарядка iPhone, iPad и MacBook Air.', specs: [['Мощность', '30 Вт']] }),
    P({ id: 'acc-cable', cat: 'accessories', brand: 'uBear', name: 'Кабель USB-C 60 Вт, 1.2 м, чёрный', price: 990, art: 'cable', tone: 'black', rating: 4.6, votes: 41, desc: 'Нейлоновая оплётка, выдерживает 30 000 перегибов.', specs: [['Мощность', '60 Вт'], ['Длина', '1.2 м']] }),
    P({ id: 'acc-magsafe', cat: 'accessories', brand: 'Apple', name: 'Зарядное устройство MagSafe 25 Вт', price: 4990, art: 'magsafe', tone: 'silver', rating: 4.8, votes: 29, desc: 'Примагничивается точно и заряжает быстро.', specs: [['Мощность', '25 Вт']] }),
    P({ id: 'acc-pb10', cat: 'accessories', brand: 'Xiaomi', name: 'Пауэрбанк Xiaomi 10 000 мА·ч, 22.5 Вт', price: 2490, art: 'powerbank', tone: 'graphite', rating: 4.7, votes: 55, desc: 'Два полных заряда смартфона в кармане.', specs: [['Ёмкость', '10 000 мА·ч'], ['Мощность', '22.5 Вт']] }),
    P({ id: 'acc-bag14', cat: 'accessories', brand: 'uBear', name: 'Сумка для ноутбука 14", серая', price: 2490, art: 'bag', tone: 'steel', rating: 4.7, votes: 15, desc: 'Мягкая защита и карман для зарядки.', specs: [['Диагональ', 'до 14"']] }),
    P({ id: 'acc-mouse', cat: 'accessories', brand: 'Logitech', name: 'Мышь Logitech M240, графит', price: 1490, art: 'mouse', tone: 'graphite', rating: 4.6, votes: 23, desc: 'Тихие клики и год работы от одной батарейки.', specs: [['Подключение', 'Bluetooth']] }),
    P({ id: 'acc-hub', cat: 'accessories', brand: 'uBear', name: 'USB-C хаб 7-в-1, серый', price: 3490, art: 'powerbank', tone: 'steel', rating: 4.6, votes: 11, desc: 'HDMI 4K, картридер и три USB в одном корпусе.', specs: [['Портов', '7']] }),
    P({ id: 'acc-hdmi', cat: 'accessories', brand: 'uBear', name: 'Кабель HDMI 2.1 8K, 2 м', price: 1290, art: 'cable', tone: 'graphite', rating: 4.7, votes: 19, desc: 'Для консолей нового поколения и 4K 120 Гц.', specs: [['Стандарт', 'HDMI 2.1'], ['Длина', '2 м']] }),
    P({ id: 'acc-bracket', cat: 'accessories', brand: 'Kromax', name: 'Кронштейн для ТВ 32-65", наклонный', price: 2990, art: 'tv', tone: 'black', rating: 4.6, votes: 27, desc: 'Выдерживает до 45 кг, монтаж за 20 минут.', specs: [['Диагональ', '32-65"'], ['Нагрузка', 'до 45 кг']] }),
    P({ id: 'acc-surge', cat: 'accessories', brand: 'Pilot', name: 'Сетевой фильтр Pilot S, 5 розеток, 3 м', price: 1190, art: 'plug', tone: 'white', rating: 4.5, votes: 36, desc: 'Защита техники от скачков напряжения.', specs: [['Розеток', '5'], ['Длина', '3 м']] })
  ];

  var REVIEWS = {
    'ip16pro': [
      { name: 'Дмитрий К.', date: '18 июля 2026', stars: 5, text: 'Перешёл с 13 Pro, разница огромная: камера, автономность, экран. В «Ракете» помогли перенести данные прямо в магазине.' },
      { name: 'Алёна С.', date: '2 июля 2026', stars: 5, text: 'Брала в рассрочку, оформили за 15 минут. Телефон огонь, цвет красивее, чем на фото.' },
      { name: 'Игорь В.', date: '14 июня 2026', stars: 4, text: 'К телефону вопросов нет. Хотелось бы больше цветов в наличии, но мой привезли за день.' }
    ],
    's24u': [
      { name: 'Марина Ш.', date: '9 июля 2026', stars: 5, text: 'Стилус решает для работы. Экран лучший из всех, что видела. Спасибо консультанту за подбор чехла.' },
      { name: 'Павел Т.', date: '21 июня 2026', stars: 5, text: 'Камера с 200 Мп это что-то. Снимал концерт с дальних рядов, кадры чёткие.' }
    ],
    'mba13': [
      { name: 'Ксения Л.', date: '11 июля 2026', stars: 5, text: 'Для учёбы и монтажа рилсов идеален. Держит заряд весь день, реально.' },
      { name: 'Артём Н.', date: '28 июня 2026', stars: 5, text: 'Тихий, лёгкий, быстрый. Помогли с настройкой и наклеили плёнку.' }
    ],
    'lgc4-55': [
      { name: 'Сергей Б.', date: '5 июля 2026', stars: 5, text: 'После обычного LED это другая вселенная. Чёрный космос в фильмах. Доставили и повесили в тот же день.' }
    ],
    'airpods-pro2': [
      { name: 'Олеся М.', date: '16 июля 2026', stars: 5, text: 'Шумодав спасает в маршрутке. Оригинал, проверили серийник при мне.' },
      { name: 'Роман Д.', date: '30 июня 2026', stars: 4, text: 'Звук отличный, но амбушюры пришлось подбирать. В магазине дали примерить размеры.' }
    ],
    'ps5-slim': [
      { name: 'Никита Ф.', date: '13 июля 2026', stars: 5, text: 'Мечта сбылась. Взял в комплекте со вторым геймпадом, вышло выгоднее.' }
    ],
    'station2': [
      { name: 'Юлия П.', date: '8 июля 2026', stars: 5, text: 'Алиса теперь управляет светом во всей квартире. Настроили сценарии прямо в магазине.' }
    ],
    'roborock-q8': [
      { name: 'Владимир Е.', date: '25 июня 2026', stars: 5, text: 'С двумя котами дома это спасение. Карту построил с первого раза.' }
    ]
  };

  window.RAKETA = {
    store: {
      name: 'Ракета',
      city: 'Магнитогорск',
      address: 'Проспект Карла Маркса, 92',
      addressFull: '455026, Челябинская область, Магнитогорск, проспект Карла Маркса, 92 (95-й микрорайон, Правобережный район)',
      phone: '+7 908 089-52-68',
      phoneHref: 'tel:+79080895268',
      hours: 'Ежедневно с 10:00 до 20:00',
      email: 'hello@raketa-mgn.ru',
      rating: 4.9,
      ratingCount: 176,
      gis: 'https://2gis.ru/magnitogorsk/search/%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D0%B0/firm/70000001043756070/58.977668%2C53.409802'
    },
    delivery: { freeFrom: 5000, courier: 300 },
    promo: { 'РАКЕТА10': 0.10 },
    categories: CATEGORIES,
    products: PRODUCTS,
    reviews: REVIEWS
  };
})();
